%% BEV Thermal Management System, Sensitivity to Passenger Count
%
% This example models a Battery Electric Vehicle (BEV) model with a thermal
% management system. It is used to measure the sensitivity of the design to
% the number of passengers carried in the vehicle.
%
% Copyright 2021-2024 The MathWorks, Inc.

%% Model

open_system('BEV_Thermal_Management')

set_param(find_system('BEV_Thermal_Management','MatchFilter',@Simulink.match.allVariants,'FindAll', 'on','SearchDepth',1,'type','annotation','Tag','ModelFeatures'),'Interpreter','off')

%% Cabin Subsystem
%
% Adding additional passengers will affect the amount of moisture and CO2
% in the cabin air.  It also adds additional heat to the cabin.  These
% effects are added by using the number of passengers as a parameter to
% scale the amount of moisture, CO2, and heat supplied to the cabin.
%
% <matlab:open_system('BEV_Thermal_Management');open_system('BEV_Thermal_Management/Cabin','force'); Open Subsystem>

open_system('BEV_Thermal_Management/Cabin','force')

%% Driveline Subsystem
%
% Adding additional passengers will affect the vertical load on the tires
% which will increase the rolling resistance.  This effect is accounted for
% by using the number of passengers as a parameter to scale the passenger
% mass in the vehicle body.
%
% <matlab:open_system('BEV_Thermal_Management');open_system('BEV_Thermal_Management/Driveline','force'); Open Subsystem>

open_system('BEV_Thermal_Management/Driveline','force')

%% Sensitivity Analysis: Passenger Count
%
% The thermal management system is tested in a drive and charge scenario.
% The vehicle must be driven a specific distance.  The driver accelerates
% to cruising speed and holds it there until the battery SOC reaches a
% lower threshold.  The driver then decelerates and waits as the battery is
% charged using a CCCV profile for 30 minutes. This cycle is repeated until
% the vehicle reaches the specified distance.
%
% The sensitivity of the design to the number of passengers in the vehicle
% is tested by performing a parameter sweep.  The number of passengers is
% increased from 1 to 5 and the energy losses are measured.  The diagrams
% below show the increase in energy loss, and they are generated by the
% code
% <matlab:open('sensitivityPassCount'); sensitivityPassCount>.  

sensitivityPassCount

%%
% Plot of results for lowest number of passengers

disp(['Results for ' num2str(passNumbEn(1).numPass) ' passenger(s).'])
plotEnergySankey(passNumbEn(1));

%%
% Plot of results for highest number of passengers

disp(['Results for ' num2str(passNumbEn(end).numPass) ' passenger(s).'])
plotEnergySankey(passNumbEn(end));

%%
bdclose('BEV_Thermal_Management')


%%
%clear all
close all
