%% This script creates the Figure 9 of the paper
% Description: This script creates the figures for figure 8 of the paper
%              For this case the cabin setpoint temperature is increased from
%              22°C to 32°C while the number of passenger is kept constant to 5
%              THIS SCRIPT LOADS AND USES SAVED SIMULATION DATA
%-----------------
% Copyright 2022-2024 The MathWorks, Inc.
%-----------------

%% Implementation
%% 1) Load simulation results
% This variable can be generated by calling the script sensitivityCabinSetpoint
if ~exist('setpointCabinEn','var')
    error('Create the results required for the plot by running the script sensitivityCabinSetpoint.m')
end

% The simulation results from sensitivitySetpointCabin.m will give the same
% results as in the paper provided you did not change the model and the simulation script

%% 2) Plot the figures
% First plot the configuration with 22°C
plotEnergySankey(setpointCabinEn(1));


set(gcf,'Units','centimeters','Position',[1,1,10,10])
set(gca,'Position',[0,0,1,1]);

% Assemble location for saving figure
temp_thisFolder     =  fileparts(which(mfilename));
figFolder = [temp_thisFolder filesep 'Figures'];
if(~isfolder(figFolder))
    mkdir(figFolder)
end

print(gcf,[figFolder filesep 'Sankey22deg'],'-djpeg','-r300')

% Then plot the configuration with 32°C passengers
plotEnergySankey(setpointCabinEn(end));

set(gcf,'Units','centimeters','Position',[1,1,10,10])
set(gca,'Position',[0,0,1,1]);

print(gcf,[figFolder filesep 'Sankey32deg'],'-djpeg','-r300')
