%% BEV Thermal Management System, Sensitivity to Cabin Setpoint
%
% This example models a Battery Electric Vehicle (BEV) model with a thermal
% management system. It is used to measure the sensitivity of the design to
% the setpoint of the cabin temperature.
%
% Copyright 2021-2024 The MathWorks, Inc.

%% Model

open_system('BEV_Thermal_Management')

set_param(find_system('BEV_Thermal_Management','MatchFilter',@Simulink.match.allVariants,'FindAll', 'on','SearchDepth',1,'type','annotation','Tag','ModelFeatures'),'Interpreter','off')

%% Cabin Air Control
%
% The setpoint temperature for the cabin affects when the blower and the
% PTC should be turned on. The setpoint temperature is set within the model
% and passed to the control logic to turn these components on or off.
%
% Here is where the cabin temperature setpoint is specified.  It is passed
% via a Simulink signal to the control subsystem
%
% <matlab:open_system('BEV_Thermal_Management');open_system('BEV_Thermal_Management/Scenario','force'); Open Subsystem>

open_system('BEV_Thermal_Management/Scenario','force')

%%
% Here is where the blower and PTC control logic is modeled.  The setpoint
% is an input to this logic.
% 
% <matlab:open_system('BEV_Thermal_Management');open_system('BEV_Thermal_Management/Controls/Cabin%20Air%20Control','force'); Open Subsystem>

open_system('BEV_Thermal_Management/Controls/Cabin Air Control','force')


%% Sensitivity Analysis: Passenger Count
%
% The thermal management system is tested in a drive and charge scenario.
% The vehicle must be driven a specific distance.  The driver accelerates
% to cruising speed and holds it there until the battery SOC reaches a
% lower threshold.  The driver then decelerates and waits as the battery is
% charged using a CCCV profile for 30 minutes. This cycle is repeated until
% the vehicle reaches the specified distance.
%
% The sensitivity of the design to the cabin setpoint temperature 
% is tested by performing a parameter sweep.  The diagrams
% below show the increase in energy loss, and they are generated by the
% code <matlab:open('sensitivityCabinSetpoint'); sensitivityCabinSetpoint>. 
% The plot below shows the impact of the number of passengers on the
% vehicle losses

sensitivityCabinSetpoint

%% 
% Plot of results for lowest temperature setpoint 
disp(['Cabin Temperature Setpoint: ' sprintf('%3.2f',setpointCabinEn(1).cabinSetpointTemp)])
plotEnergySankey(setpointCabinEn(1));

%%
% Plot of results for highest temperature setpoint 
disp(['Cabin Temperature Setpoint: ' sprintf('%3.2f',setpointCabinEn(end).cabinSetpointTemp)])
plotEnergySankey(setpointCabinEn(end));

%%
bdclose('BEV_Thermal_Management')


%%
%clear all
close all
