% Description: For this case the cabin setpoint temperature is increased from
%              22°C to 32°C while the number of passenger is kept constant to 5
%              THIS SCRIPT LOADS AND USES SAVED SIMULATION DATA
%-----------------
% Copyright 2022-2023 The MathWorks, Inc.
%-----------------

%% 1) Load simulation results
% If there are already simulation results in the workspace those results
% will be used

prj     =  matlab.project.rootProject;
figLink = append(prj.RootFolder,'\Overview\Figures');

% This variable can be generated by calling the script sensitivityCabinSetpoint
if ~exist('setpointCabinEn','var')
    error('Create the results required for the plot by running the script sensitivityCabinSetpoint.m')
end

% The simulation results from sensitivityCabinSetpoint.m will give the same
% results as in the paper provided you did not change the model and the simulation script

% Get the 22°C, 26°C and 32°C results
S22 = setpointCabinEn(1).hvac;
S26 = setpointCabinEn(3).hvac;
S32 = setpointCabinEn(end).hvac;

% Colors to be used in the plots
Colors = [215, 136, 36; 0  , 118, 168; 255, 206, 94; 255, 255, 255; 153,153,153;0,0,0]/255;

% Get the energy components and the labels. The test was done on cooling so we exclude
% the energy components of heater and PTC since they will not be active in the  simulation
hvacEn   = [round([S22.energyCmpr; S22.energyFan; S22.energyBlwr; S22.energyPmps  + S22.energyDCDC ],2),...
            round([S26.energyCmpr; S26.energyFan; S26.energyBlwr; S26.energyPmps  + S26.energyDCDC ],2),...
            round([S32.energyCmpr; S32.energyFan; S32.energyBlwr; S32.energyPmps  + S32.energyDCDC ],2)];

% Set the corresponding labels
labels = categorical({'Compressor'; 'Condenser fan'; 'Blower';'Pumps/DC-DC'});

% Sort values and labels in descending order for better visibility
[reqEnSrtd,I] = sort(hvacEn,'descend');
labelsSrtd    = labels(I);

% Create bar plot
h1 = bar(reqEnSrtd,'FaceColor','flat');

% Set axes dimensions and layout
set(gca,'XLim',[0.5,size(hvacEn,1)+0.5],'YLim',[0,max(max(hvacEn))*1.1]);
set(gca, 'XTick',1:size(hvacEn,1),'XTickLabel', labelsSrtd,'FontSize',11);
ylabel('HVAC Losses in kWh');

% Set color and dimensions of the bar plot
h1(1).CData = repmat(Colors(1,:),4,1);
h1(2).CData = repmat(Colors(2,:),4,1);
h1(3).CData = repmat(Colors(3,:),4,1);
h1(1).BarWidth  = 1; h1(2).BarWidth  = 1; h1(3).BarWidth = 1;

title('Compare HVAC Losses')
